// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Web is not supported by this template. Run flutterfire configure.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'iOS is not supported by this template. Run flutterfire configure.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'MacOS is not supported by this template. Run flutterfire configure.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'Windows is not supported by this template. Run flutterfire configure.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Linux is not supported by this template. Run flutterfire configure.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATILkwroF7NrPhQ7qgQgpD-t16b862i_4',
    appId: '1:685728481364:android:39b129c026dd7f958eedc1',
    messagingSenderId: '685728481364',
    projectId: 'habit-tracker-mvp-7cc72',
  );
}
